apiVersion: v1
kind: Service
metadata:
  name: mlops-service
  namespace: mlops-major
  labels:
    app: mlops-app
spec:
  selector:
    app: mlops-app
  # Use type: LoadBalancer on cloud (AWS/GCP/Azure). For local (minikube/kind), use NodePort.
  type: LoadBalancer
  ports:
  - port: 80        # external port
    targetPort: 5001
    protocol: TCP
    name: http
